In [1]:
%matplotlib inline
import tensorflow as tf, numpy as np
from matplotlib import pyplot as plt
plt.style.use('ggplot')

np.set_printoptions(precision=4, suppress=True, linewidth=100)
np.random.seed(42)

### Softmax

In [11]:
tf.reset_default_graph()
with tf.Graph().as_default():
    a = tf.constant([[5., 1., 3., -3., -3., 0.]])
    # softmax with cross entropy
    result = tf.nn.softmax_cross_entropy_with_logits(logits=a, labels=[[1., 0., 0., 0., 0., 0]])
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print(tf.nn.softmax(a).eval())
        print( sess.run(result) )

[[ 0.8613  0.0158  0.1166  0.0003  0.0003  0.0058]]
[ 0.1493]


### Sigmoid

In [13]:
tf.reset_default_graph()
with tf.Graph().as_default():
    a = tf.constant([[5., 1., 3., -3., -3., 0.]])
    # softmax with cross entropy
    result = tf.nn.sigmoid_cross_entropy_with_logits(logits=a, labels=[[1., 0., 0., 0., 0., 0]])
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print(tf.nn.sigmoid(a).eval())
        print( sess.run(result) )

[[ 0.9933  0.7311  0.9526  0.0474  0.0474  0.5   ]]
[[ 0.0067  1.3133  3.0486  0.0486  0.0486  0.6931]]


### Embedding

In [16]:
tf.reset_default_graph()
with tf.Graph().as_default():
    a = tf.constant([1, 0, 2])
    embedding = tf.constant([[0., 0., 0.],
                             [1., 1., 1.],
                             [2., 2., 2.]])
    lookup = tf.nn.embedding_lookup(embedding, a)
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print( sess.run(lookup) )

[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 2.  2.  2.]]
