In [1]:
import tensorflow as tf, numpy as np
from matplotlib import pyplot as plt
plt.style.use('ggplot')

np.set_printoptions(precision=4, suppress=True, linewidth=100)
np.random.seed(42)

### Tensorflow load model without source code (沒有source code的狀況...)

In [17]:
model_dir = "./model/linear"
with tf.Session() as sess:
    latestCkpt = tf.train.latest_checkpoint(model_dir)
    saver = tf.train.import_meta_graph(latestCkpt + ".meta")
    saver.restore(sess, latestCkpt)
    # print( sess.graph.get_tensor_by_name("inputs/placeholder_x:0") )
    for n in sess.graph.get_operations():
        print(n.name)

INFO:tensorflow:Restoring parameters from ./model/linear\linear_model-199
Tensor("inputs/placeholder_x:0", shape=(?,), dtype=float32)


### Softmax

In [2]:
tf.reset_default_graph()
with tf.Graph().as_default():
    inputs = tf.constant([[5., 1., 3., -3., -3., 0.]])
    labels = [[1., 0., 0., 0., 0., 0.]]
    # softmax with cross entropy
    result = tf.nn.softmax_cross_entropy_with_logits(logits=inputs, labels=labels)
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print("softmax: ", tf.nn.softmax(inputs).eval())
        print("labels: ", labels)
        print()
        print("cross entropy: ", sess.run(result) )

softmax:  [[ 0.8613  0.0158  0.1166  0.0003  0.0003  0.0058]]
labels:  [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

cross entropy:  [ 0.1493]


### Sigmoid

In [16]:
tf.reset_default_graph()
with tf.Graph().as_default():
    inputs = tf.constant([[5., 1., 3., -3., -3., 0.]])
    labels = [[1., 0., 0., 0., 0., 0.]]
    # sigmoid with cross entropy
    result = tf.nn.sigmoid_cross_entropy_with_logits(logits=inputs, labels=labels)
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print("sigmoid: ", tf.nn.sigmoid(inputs).eval())
        print("labels: ", labels)
        print()
        print("cross entropy: ", sess.run(result) )

sigmoid:  [[ 0.9933  0.7311  0.9526  0.0474  0.0474  0.5   ]]
labels:  [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

cross entropy:  [[ 0.0067  1.3133  3.0486  0.0486  0.0486  0.6931]]


### Matrix Operation Example

In [3]:
tf.reset_default_graph()
with tf.Graph().as_default():
    data = tf.constant([[1., -1.]])
    w = tf.constant([[ 1., -1.], 
                     [-2., 1.]])
    b = tf.constant([1., 0.])
    result = tf.matmul(data, w) + b
    sigmoid = tf.nn.sigmoid(result)
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print( sess.run(sigmoid) )

[[ 0.982   0.1192]]


### Embedding

In [16]:
tf.reset_default_graph()
with tf.Graph().as_default():
    a = tf.constant([1, 0, 2])
    embedding = tf.constant([[0., 0., 0.],
                             [1., 1., 1.],
                             [2., 2., 2.]])
    lookup = tf.nn.embedding_lookup(embedding, a)
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print( sess.run(lookup) )

[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 2.  2.  2.]]


### MF Predict

In [4]:
tf.reset_default_graph()
with tf.Graph().as_default():
    um = tf.constant([[  3.5,  4.7, 0.87, 1.87,  0.8],
                      [ 4.87,  5.6,  2.1, 3.87, 4.57],
                      [ 5.87, 4.78, 1.87, 1.2,   3.6],
                      [  1.7,  3.2,  2.9, 2.87,  2.6]])
    bu = tf.constant([[0.1], [0.2], [0.3], [0.4]])
    bm = tf.constant([[0.8, 0.7, 0.6, 0.5, 0.4]])
    bg = tf.constant([0.5])
    result = um + bu + bm + bg
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        print( sess.run(result) )

[[ 4.9   6.    2.07  2.97  1.8 ]
 [ 6.37  7.    3.4   5.07  5.67]
 [ 7.47  6.28  3.27  2.5   4.8 ]
 [ 3.4   4.8   4.4   4.27  3.9 ]]
